#!/bin/bash

#############################################################################
# Generate repos.ini from GitLab API
# 
# Purpose: Query GitLab API for all repositories and generate repos.ini
# Usage:   ./generate-repos.sh [--output FILE]
#
# Options:
#   --output FILE     Output file (default: repos.ini)
#   --include-forks   Include forked repositories
#   --archived        Include archived repositories
#
#############################################################################

set -euo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Source config for GitLab credentials
source "${SCRIPT_DIR}/lib-config.sh"
load_config

# Defaults
OUTPUT_FILE="${SCRIPT_DIR}/repos.ini"
INCLUDE_FORKS=false
INCLUDE_ARCHIVED=false

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --output)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --include-forks)
            INCLUDE_FORKS=true
            shift
            ;;
        --archived)
            INCLUDE_ARCHIVED=true
            shift
            ;;
        -h|--help)
            echo "Usage: $0 [--output FILE] [--include-forks] [--archived]"
            echo ""
            echo "Options:"
            echo "  --output FILE     Output file (default: repos.ini)"
            echo "  --include-forks   Include forked repositories"
            echo "  --archived        Include archived repositories"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}Generating repos.ini from GitLab API${NC}"
echo -e "GitLab Host: ${GITLAB_HOST}"
echo -e "GitLab User: ${GITLAB_USER}"
echo ""

# Check for required tools
if ! command -v curl &> /dev/null; then
    echo "ERROR: curl is required but not installed"
    exit 1
fi

if ! command -v jq &> /dev/null; then
    echo "ERROR: jq is required but not installed"
    exit 1
fi

# Check for API token
if [[ -z "${GITLAB_TOKEN:-}" ]]; then
    echo "ERROR: GitLab API token not configured in config.ini"
    echo "Add api_token under [source] section"
    exit 1
fi

# Build GitLab API URL
API_URL="https://${GITLAB_HOST}/api/v4/users/${GITLAB_USER}/projects"
API_PARAMS="?per_page=100&owned=true"

if [[ "$INCLUDE_ARCHIVED" == false ]]; then
    API_PARAMS="${API_PARAMS}&archived=false"
fi

echo -e "${BLUE}Querying GitLab API...${NC}"

# Query GitLab API
RESPONSE=$(curl -s --header "PRIVATE-TOKEN: ${GITLAB_TOKEN}" "${API_URL}${API_PARAMS}")

# Check for API errors
if echo "$RESPONSE" | jq -e '.error' &>/dev/null; then
    ERROR_MSG=$(echo "$RESPONSE" | jq -r '.error // .message // "Unknown error"')
    echo "ERROR: GitLab API error: $ERROR_MSG"
    exit 1
fi

# Count repos
REPO_COUNT=$(echo "$RESPONSE" | jq 'length')
echo -e "${GREEN}Found ${REPO_COUNT} repositories${NC}"
echo ""

# Generate repos.ini
echo -e "${BLUE}Generating ${OUTPUT_FILE}...${NC}"

cat > "${OUTPUT_FILE}" << 'EOF'
# Repository List Configuration
# Generated by generate-repos.sh
# 
# Format: name|visibility|description
# - name: Repository slug (used for both local path and remote URL)
# - visibility: public, private, or internal
# - description: Repository description (optional)
#
# Local path is derived from: ${local_repo_root}/${name}
# GitLab SSH URL is derived from: git@${gitlab_host}:${gitlab_user}/${name}.git
# GitHub SSH URL is derived from: git@${github_host}:${github_user}/${name}.git
#

[repositories]
EOF

# Process each repository
echo "$RESPONSE" | jq -c '.[]' | while read -r repo; do
    NAME=$(echo "$repo" | jq -r '.path')
    VISIBILITY=$(echo "$repo" | jq -r '.visibility')
    DESCRIPTION=$(echo "$repo" | jq -r '.description // ""' | tr '|' '-' | tr '\n' ' ' | sed 's/[[:space:]]*$//')
    FORKED=$(echo "$repo" | jq -r '.forked_from_project // empty')
    
    # Skip forks if not requested
    if [[ -n "$FORKED" ]] && [[ "$INCLUDE_FORKS" == false ]]; then
        echo -e "  ${YELLOW}Skipping fork: ${NAME}${NC}"
        continue
    fi
    
    echo "  Adding: ${NAME} (${VISIBILITY})"
    echo "${NAME}|${VISIBILITY}|${DESCRIPTION}" >> "${OUTPUT_FILE}"
done

echo ""
echo -e "${GREEN}Generated: ${OUTPUT_FILE}${NC}"
echo ""

# Show summary
echo -e "${CYAN}Summary:${NC}"
TOTAL=$(grep -c '^[^#\[]' "${OUTPUT_FILE}" 2>/dev/null || echo "0")
PUBLIC=$(grep '|public|' "${OUTPUT_FILE}" | wc -l || echo "0")
PRIVATE=$(grep '|private|' "${OUTPUT_FILE}" | wc -l || echo "0")
INTERNAL=$(grep '|internal|' "${OUTPUT_FILE}" | wc -l || echo "0")

echo "  Total repositories: ${TOTAL}"
echo "  Public: ${PUBLIC}"
echo "  Private: ${PRIVATE}"
echo "  Internal: ${INTERNAL}"
echo ""
echo -e "${BLUE}Next steps:${NC}"
echo "  1. Review repos.ini and remove any repos you don't want to migrate"
echo "  2. Run: ./gitlab-to-github-migration.sh --dry-run"
